# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# What combinations to test
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "Current"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%

build_script:
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm ls
  - npm test
  - IF %nodejs_version% GEQ 4 rmdir /s /q node_modules
  - IF %nodejs_version% GEQ 4 npm install -g yarn
  - IF %nodejs_version% GEQ 4 yarn install
  - IF %nodejs_version% GEQ 4 yarn test
