os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "node"

script:
  - npm test
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\\1/') -le 4 ] || rm -rf node_modules"
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\\1/') -le 4 ] || npm install -g yarn"
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\\1/') -le 4 ] || yarn install"
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\\1/') -le 4 ] || yarn test"
