os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

script:
  - npm test
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\1/') -lt 4 ] || rm -rf node_modules"
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\1/') -lt 4 ] || npm install -g yarn"
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\1/') -lt 4 ] || yarn install"
  - "[ $(node --version | sed -E 's/^v([0-9]*)[.].*/\1/') -lt 4 ] || yarn test"
